#ifndef LOGGINGPARAMS_H
#define LOGGINGPARAMS_H
#include <QString>

enum debugLevels {LOGGALLERY,LOGPARAM,LOGFFT,LOGWAVIO,LOGSYNTHES,LOGDISPATCH,LOGSOUND,
                  LOGRXFUNC,LOGTXFUNC,LOGSYNCSTATE,LOGSYNCPROCESSSTATE,LOGSYNCEXTRACT,LOGSYNCEVAL,LOGSYNCACCEPTED,LOGSYNCREJECTED,LOGSYNCMATCH,LOGSYNCLOST,LOGSLANT,
                  LOGMODES,LOGFTP,LOGIMAG,LOGSCOPE,LOGCAM,LOGRXMAIN,LOGTXMAIN,LOGEDIT,LOGRIGCTRL,
                  LOGDRMDEMOD,LOGDRMSRC,LOGDRMMOT,LOGDRMTX,LOGDRMTXMOT,LOGDRMTXCOD,LOGDRMTXAAA,LOGXML,
                  LOGFSKID,LOGVISCODE,LOGRETRACE,LOGCALIB,LOGNOTIFY,LOGPERFORM,LOGALL=99};

#define NUMDEBUGLEVELS (LOGPERFORM+1)

extern QString levelStr[NUMDEBUGLEVELS];
#endif // LOGGINGPARAMS_H
